name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- release

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image and push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'registry.ap-northeast-1.aliyuncs.com(Tokyo)'
        repository: 'sakuradon/outline'
        command: 'buildAndPush'
        Dockerfile: './.azure/Dockerfile'
        buildContext: '.'
        tags: '$(Build.BuildNumber)'